service: reviewdb

frameworkVersion: ">= 1.6.0 <2.0.0"

package:
  individually: true
  include:
    - psycopg2/**/*
  exclude:
    - venv/**/*
    - ./.aws-sam/**/*
  excludeDevDependencies: false

custom:
  pythonRequirements:
    layer: true
    zip: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  create:
    handler: create.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: reviews
          method: post
  read:
    handler: read.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: reviews/{review_hash}
          method: get

  fetch:
    handler: fetch.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: fetch/{review_hash}
          method: get

  sentimentalize:
    handler: sentimentalize.handler
    layers:
      - {Ref: PythonRequirementsLambdaLayer}

plugins:
  - serverless-python-requirements
